// Sprite variables
let sprite,
    deckImg,
    optionBox,
    option1,
    option2,
    option3,
    options = [],
    longBoard,
    endText,
    koiText,
    scoreBox1,
    scoreBox2,
    roundText,
    resultBackground,
    resultRoundText,
    youText,
    cpuText,
    youResultText,
    cpuResultText,
    drawText,
    startText,
    blackBar,
    bigCard,
    startBackground,
    randomCard1,
    randomCard2,
    turnTex,
    defeatText,
    restartText,
    winTexture,
    defeatTexture,
    drawTexture,
    resultText,
    finger;
